# Note: The sub-headings / sections are optional and are removed from the config parser anyway. The only important thing is the [darts] heading
[darts]
ee-project = "your-project-here"

[darts.paths]
input-data-dir = "data/input"
output-data-dir = "data/output"
model-dir = "models"

[darts.segmentation]
patch-size = 1024
overlap = 128
batch-size = 2
reflection = 32
