name: darts_albedo_forge_only
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy[version='>=1.26.3,<2']
  - xarray[version='>=2024.9.0']
  - rich[version='>=13.9.2']
  - cyclopts[version='>=2.9.9']
  - h5netcdf[version='>=1.3.0']
  - rioxarray[version='>=0.17.0']
  - geopandas[version='>=1.0.1']
  - shapely[version='>=2.0.0']
  - scikit-image[version='>=0.20']
  - scipy[version='>=1.14.1']
  - gdal==3.8.5
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - lovely-tensors[version='>=0.1.17']
  - lovely-numpy[version='>=0.2.13']
  - segmentation-models-pytorch[version='>=0.3.4']
  - ca-certificates
  - certifi
  - openssl
  - jsonschema
  - protobuf[version='!=3.19.5,>=3.15.3']
  - aiosignal
  - frozenlist
  - pyarrow[version='>=6.0.1']
  - pip:
    - cucim-cu12==24.10.0
    - cupy-cuda12x==13.3.0
    - fastrlock==0.8.2
    - msgpack==1.1.0
    - ray==2.37.0