# Note: The sub-headings / sections are optional and are removed from the config parser anyway. The only important thing is the [darts] heading
[darts]
ee-project = "pdg-project-406720"

[darts.paths]
sentinel2-dir = "/taiga/pdg-rts/pdg-files/ftp_shared_files/public/jokuep001/S2"
orthotiles-dir = "/taiga/pdg-rts/data/input/planet/PSOrthoTile"
scenes-dir = "/taiga/toddn/pdg-rts/input/planet/PSScene"
output-data-dir = "/taiga/pdg-rts/rts_dataset01/output"
model-dir = "/taiga/pdg-rts/rts_dataset01/models"
tcvis-model-name = "/taiga/pdg-rts/pdg-files/s2-tcvis-unetpp-resnext101-bestfromsweep_2025-01-15_fix.ckpt"
notcvis-model-name = "RTS_v6_notcvis.pt"
arcticdem-slope-vrt = "/taiga/pdg-rts/rts_dataset01/input/ArcticDEM/slope.vrt"
arcticdem-elevation-vrt = "/taiga/pdg-rts/rts_dataset01/input/ArcticDEM/elevation.vrt"
arcticdem-dir =  "/taiga/pdg-rts/rts_dataset01/input/ArcticDEM"
tcvis-dir = "/home/toddn/darts-nextgen/tcvis_dir"

[darts.preprocess]
tpi-outer-radius = 100
tpi-inner-radius = 0

[darts.segmentation]
patch-size = 1024
overlap = 256
batch-size = 2
reflection = 32

[darts.training]
bands = [
    'blue',
    'green',
    'red',
    'nir',
    'ndvi',
    'tc_brightness',
    'tc_greenness',
    'tc_wetness',
    'relative_elevation',
    'slope',
]
train-data-dir = "data/training"
include-allzero = false
include-nan-edges = true
