[workspace]
authors = ["Tobias Hölzer <tobiashoelzer@hotmail.com>"]
channels = ["conda-forge"]
name = "darts-nextgen"
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
# google-cloud-sdk = ">=525.0.0,<526" # Not availble on windows...
uv = ">=0.7.12,<0.8"

[feature.cuda118]
channels = ["nvidia", "conda-forge"]
platforms = ["linux-64", "win-64"]
dependencies = { cuda = {version = "11.8.*", channel = "nvidia"} }

[feature.cuda121]
channels = ["nvidia", "conda-forge"]
platforms = ["linux-64", "win-64"]
dependencies = { cuda = {version = "12.1.*", channel = "nvidia"} }

[feature.cuda126]
channels = ["nvidia", "conda-forge"]
platforms = ["linux-64", "win-64"]
dependencies = { cuda = {version = "12.6.*", channel = "nvidia"} }

[environments]
cuda118 = ["cuda118"]
cuda121 = ["cuda121"]
cuda126 = ["cuda126"]
