[darts]
orthotiles-dir = "/home/toddn/darts-nextgen/data/input/planet/PSOrthoTile"
scenes-dir = "/home/toddn/darts-nextgen/data/input/planet/PSScene"
arcticdem-dir = "/home/toddn/darts-nextgen/rts_dataset01/input/ArcticDEM"
arcticdem-slope-vrt = "/home/toddn/darts-nextgen/rts_dataset01/input/ArcticDEM/slope.vrt"
arcticdem-elevation-vrt = "/home/toddn/darts-nextgen/rts_dataset01/input/ArcticDEM/elevation.vrt"
output-data-dir = "/home/toddn/darts-nextgen/rts_dataset01/output"
model-dir = "/home/toddn/darts-nextgen/rts_dataset01/models"
tcvis-dir= "/home/toddn/darts-nextgen/tcvis_dir"
ee-project = "pdg-project-406720"