"""Legacy pipeline module."""

from darts.legacy_pipeline.planet_fast import LegacyNativePlanetPipelineFast as LegacyNativePlanetPipelineFast
from darts.legacy_pipeline.planet_fast import run_native_planet_pipeline_fast as run_native_planet_pipeline_fast
from darts.legacy_pipeline.s2_fast import LegacyNativeSentinel2PipelineFast as LegacyNativeSentinel2PipelineFast
from darts.legacy_pipeline.s2_fast import run_native_sentinel2_pipeline_fast as run_native_sentinel2_pipeline_fast
